### ISSUE TITLE
Simple echo server and client

### ISSUE THREAD

**Issue by katiehsieh** [ucsd-cse125-sp23/group-1#2]
- Connects, sends data back and forth
- Verify that data received is what was sent
- Assume just one client for now

TODO:
- [x] Send/receive string messages instead of garbage data
- [x] Create Cargo target for client & server
- [x] Test with multiple client instances

**Comment by farnaf** [comment]
- Connects, sends data back and forth
- Verify that data received is what was sent
- Assume just one client for now
