### ISSUE TITLE
Resizing the window causes stretching

### ISSUE THREAD

**Issue by AW0723** [ucsd-cse125-sp23/group-1#34]

**Comment by farnaf** [comment]
@AW0723 does using aspect ratio work for this? or did you have something else in mind?

This branch uses aspect ratio to avoid stretching of objects/images: https://github.com/ucsd-cse125-sp23/group-1/tree/window-resizing

**Comment by AW0723** [comment]
> @AW0723 does using aspect ratio work for this? or did you have something else in mind?
> 
> This branch uses aspect ratio to avoid stretching of objects/images: https://github.com/ucsd-cse125-sp23/group-1/tree/window-resizing

Ohh this works, although maximizing the window still causes stretching. We'll probably want to maximize the window for the demo.

**Comment by farnaf** [comment]
Would changing the screen width/height (as well as ratio) to full screen size fix that?

Changing width = 1000 helped with that on my laptop
